const express = require('express')

const { requireApprovedRetailer } = require('../../middleware/retailerAccess')
const { retailerKycUpload } = require('../../middleware/retailerKycUpload')
const { validateObjectIdParam } = require('../../middleware/validateObjectId')
const { uploadImages } = require('../../middleware/upload')
const marketplace = require('../../controllers/Retailer Management/retailerMarketplaceController')
const account = require('../../controllers/Retailer Management/retailerAccountController')
const auth = require('../../controllers/Retailer Management/retailerAuthController')
const myProducts = require('../../controllers/Retailer Management/retailerProductController')

const router = express.Router()
router.param('id', validateObjectIdParam('id'))
router.param('offerId', validateObjectIdParam('offerId'))

// Pending-safe account, approval, and KYC flow.
router.get('/config', account.getCapabilities)
router.get('/profile', account.getProfile)
router.put('/profile', account.updateProfile)
router.get('/company', account.getCompany)
router.put('/company', account.updateCompany)
router.patch('/change-password', account.changePassword)
router.get('/addresses', account.listAddresses)
router.post('/addresses', account.addAddress)
router.put('/addresses/:id', account.updateAddress)
router.delete('/addresses/:id', account.deleteAddress)
router.get('/kyc/documents', account.getKycDocuments)
router.get('/kyc/documents/:type/download', account.downloadKycDocument)
router.post('/kyc/documents', retailerKycUpload, auth.uploadDocs)

// Products & dashboard — visible to all authenticated retailers (even pending)
router.get('/dashboard', marketplace.dashboard)
router.get('/products', marketplace.listProducts)
router.get('/products/:id', marketplace.getProduct)
router.get('/notifications', marketplace.listNotifications)
router.patch('/notifications/read-all', marketplace.readAllNotifications)
router.patch('/notifications/:id/read', marketplace.readNotification)

// Approved, active retailer business APIs.
router.use(requireApprovedRetailer)
router.get('/enquiries', marketplace.listEnquiries)
router.post('/enquiries', marketplace.createEnquiry)
router.get('/enquiries/:id', marketplace.getEnquiry)
router.patch('/enquiries/:id/cancel', marketplace.cancelEnquiry)
router.get('/enquiries/:id/messages', marketplace.listMessages)
router.post('/enquiries/:id/messages', marketplace.createBuyerMessage)
router.get('/enquiries/:id/offers', marketplace.listOffers)
router.patch('/enquiries/:id/offers/:offerId', marketplace.respondToOffer)
// Retailer's own products (retailer creates/owns these).
router.get('/my-products', myProducts.listMyProducts)
router.post('/my-products', uploadImages, myProducts.createMyProduct)
router.get('/my-products/:id', myProducts.getMyProduct)
router.delete('/my-products/:id', myProducts.deleteMyProduct)

router.get('/orders', marketplace.listOrders)
router.post('/orders', marketplace.createOrder)
router.get('/orders/:id', marketplace.getOrder)
router.patch('/orders/:id/cancel', marketplace.cancelOrder)
router.get('/orders/:id/tracking', marketplace.tracking)
router.get('/subscription/plans', account.getPlans)
router.get('/subscription/current', account.getCurrentSubscription)

module.exports = router
